force-app/main/default/objects/Lead/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>The capital city of this country.</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ISO_Code_2__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code_2__c</fullName>
    <description>The ISO code of the country of this lead.</description>
    <label>ISO Code 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ISO_Code_3__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code_3__c</fullName>
    <description>The three-letter country ISO code.</description>
    <label>ISO Code 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>The region of this country.</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/test/triggerHandler/LeadTriggerHandlerTest.cls
@IsTest
public with sharing class LeadTriggerHandlerTest {

    @TestSetup
    private static void init() {
        insert LeadDataFactory.createLead();
    }
    
    @IsTest
    private static void assignCountryCodeTest() {
        Lead testLead = [SELECT ISO_Code_2__c, ISO_Code_3__c, Region__c, Capital__c FROM Lead LIMIT 1];

        System.assertEquals('CZ', testLead.ISO_Code_2__c);
        System.assertEquals('CZE', testLead.ISO_Code_3__c);
        System.assertEquals('Europe', testLead.Region__c);
        System.assertEquals('Prague', testLead.Capital__c);

        testLead.Country = 'Slovakia';
        update testLead;
        testLead = [SELECT ISO_Code_2__c, ISO_Code_3__c, Region__c, Capital__c FROM Lead LIMIT 1];

        System.assertEquals('SK', testLead.ISO_Code_2__c);
        System.assertEquals('SVK', testLead.ISO_Code_3__c);
        System.assertEquals('Europe', testLead.Region__c);
        System.assertEquals('Bratislava', testLead.Capital__c);
    }
}