force-app/main/default/objects/Country_Code__mdt/Country_Code__mdt.object-meta.xml
<CustomObject>
    <description>This metadata holds custom country codes, names, capital city and regions.</description>
    <label>Country Code</label>
    <pluralLabel>Country Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Country_Code__mdt/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <description>The ISO code of a country - length of 2</description>
    <label>Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Code__mdt/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <description>The ISO code of a country - length of 3</description>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Code__mdt/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>The name of the capital city.</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Code__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>The region of this country.</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>The capital city of this country.</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ISO_Code_2__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code_2__c</fullName>
    <description>The ISO code of the country of this lead.</description>
    <label>ISO Code 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ISO_Code_3__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code_3__c</fullName>
    <description>The three-letter country ISO code.</description>
    <label>ISO Code 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>The region of this country.</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/triggerHandler/LeadTriggerHandler.cls
public with sharing class LeadTriggerHandler {
    private LeadTriggerHandler() {}

    public static void execute(final List<Lead> newValues, final Map<Id, Lead> oldMap) {
        switch on Trigger.operationType {
            when BEFORE_INSERT {
                LeadTriggerHandler.assignCountryCodes(newValues);
            }
            when BEFORE_UPDATE {
		        LeadTriggerHandler.assignCountryCodes(newValues);
            }
        }
    }

    /**
     * Assigns values to specific fields from the associated Country_Code__mdt custom metadata based on its Country value.
     */
    public static void assignCountryCodes(final List<Lead> newValues) {
        final List<Country_Code__mdt> countryCodeMdtList = Country_Code__mdt.getAll().values();
        final Map<String, Country_Code__mdt> codeToCountryCodeMap = prepareCodeToCountryCodeMap(countryCodeMdtList);
        
        for (Lead leadRecord : newValues) {
            final Country_Code__mdt countryCode = codeToCountryCodeMap.get(leadRecord.Country);
            if (countryCode != null) {
                leadRecord.ISO_Code_2__c = countryCode.Alpha2Code__c;
                leadRecord.ISO_Code_3__c = countryCode.Alpha3Code__c;
                leadRecord.Capital__c = countryCode.Capital__c;
                leadRecord.Region__c = countryCode.Region__c;
            }
        }
    }

    /**
     * Extracts ISO-Code-2 values from a list of Country Code mdt records and returns a map of codes and records.
     */
    private static Map<String, Country_Code__mdt> prepareCodeToCountryCodeMap(final List<Country_Code__mdt> countryCodeMdtList) {
        final Map<String, Country_Code__mdt> result = new Map<String, Country_Code__mdt>();
        for (Country_Code__mdt countryCodeMdt : countryCodeMdtList) {
            result.put(countryCodeMdt.Name__c, countryCodeMdt);
        }

        return result;
    }
}